export const FETCH_ALL_GAMES_REQUEST = "FETCH_ALL_GAMES_REQUEST";
export const FETCH_ALL_GAMES_SUCCESS = "FETCH_ALL_GAMES_SUCCESS";
export const FETCH_ALL_GAMES_FAILURE = "FETCH_ALL_GAMES_FAILURE";

export const ADD_GAME_ACH_TO_KANBAN = "ADD_GAME_ACH_TO_KANBAN";
